name: 🪞 Mirror to Epitech Repo
run-name: push_mirror

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    push_to_mirror:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Push to Mirror
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                  target_repo_url: ${{secrets.MIRROR_URL}}
                  ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}